language: "en"
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: true
    model_confidence: linear_norm
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
  - name: "FallbackClassifier"
    threshold: 0.3
  - name: "FormPolicy"
  - name: "MemoizationPolicy"
  - name: "TwoStageFallback"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
  - name: "AugmentedMemoizationPolicy"
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
  - name: "RulePolicy"
    core_fallback_threshold: 0.3
    nlu_fallback_threshold: 0.3
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
